In [16]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer

In [17]:
df=pd.read_csv("dataset/synthetic_logs.csv")

In [18]:
df.head()

,timestamp,source,log_message,target_label
0,27-06-2025 07:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert
3,12-07-2025 00:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status
4,02-06-2025 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status


In [19]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [20]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [21]:
df[df.source=="LegacyCRM"]

,timestamp,source,log_message,target_label
60,06-10-2025 16:55,LegacyCRM,Lead conversion failed for prospect ID 7842 du...,Workflow Error
255,03-05-2025 16:55,LegacyCRM,API endpoint 'getCustomerDetails' is deprecate...,Deprecation Warning
377,24-06-2025 12:16,LegacyCRM,Customer follow-up process for lead ID 5621 fa...,Workflow Error
1325,17-04-2025 07:33,LegacyCRM,Escalation rule execution failed for ticket ID...,Workflow Error
1734,30-04-2025 07:47,LegacyCRM,The 'ExportToCSV' feature is outdated. Please ...,Deprecation Warning
1826,23-01-2025 10:33,LegacyCRM,Support for legacy authentication methods will...,Deprecation Warning
2217,12-05-2025 09:46,LegacyCRM,Task assignment for TeamID 3425 could not comp...,Workflow Error


In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2410 entries, 0 to 2409
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   timestamp     2410 non-null   object
 1   source        2410 non-null   object
 2   log_message   2410 non-null   object
 3   target_label  2410 non-null   object
dtypes: object(4)
memory usage: 75.4+ KB


In [23]:
df.describe()

,timestamp,source,log_message,target_label
count,2410,2410,2410,2410
unique,2403,6,2265,9
top,30-08-2025 19:35,ThirdPartyAPI,Backup completed successfully.,HTTP Status
freq,2,496,60,1017


<h2>Embeddings</h2>

In [25]:
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(df["log_message"].tolist())
embeddings[:2]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\Dhanj\anaconda3\envs\log_classif\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Dhanj\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

array([[-1.02939621e-01,  3.35459411e-02, -2.20260732e-02,
         1.55101740e-03, -9.86917876e-03, -1.78956270e-01,
        -6.34409785e-02, -6.01761639e-02,  2.81109158e-02,
         5.99620491e-02, -1.72618348e-02,  1.43363548e-03,
        -1.49560034e-01,  3.15287686e-03, -5.66030927e-02,
         2.71685235e-02, -1.49891041e-02, -3.54037657e-02,
        -3.62936445e-02, -1.45410765e-02, -5.61491773e-03,
         8.75539035e-02,  4.55120578e-02,  2.50963885e-02,
         1.00187510e-02,  1.24267349e-02, -1.39923573e-01,
         7.68696293e-02,  3.14095505e-02, -4.15247958e-03,
         4.36902344e-02,  1.71250012e-02, -8.00951198e-02,
         5.74006326e-02,  1.89091656e-02,  8.55262503e-02,
         3.96398641e-02, -1.34371817e-01, -1.44360063e-03,
         3.06704035e-03,  1.76854044e-01,  4.44885530e-03,
        -1.69274509e-02,  2.24266481e-02, -4.35049310e-02,
         6.09034160e-03, -9.98169929e-03, -6.23972900e-02,
         1.07372422e-02, -6.04895083e-03, -7.14660808e-0

<h2>Clustering</h2>

In [36]:
from sklearn.cluster import DBSCAN
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
clusters=dbscan.fit_predict(embeddings)
clusters

array([0, 1, 2, ..., 0, 1, 7], shape=(2410,))

In [37]:
df['cluster']=clusters

In [45]:
df[df.cluster==1]

,timestamp,source,log_message,target_label,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1
10,08-09-2025 18:58,ModernCRM,Email server encountered a sending fault,Error,1
217,1/22/2025 5:45,BillingSystem,Mail service encountered a delivery glitch,Error,1
248,05-02-2025 23:04,ModernHR,Service disruption caused by email sending error,Critical Error,1
265,3/30/2025 23:53,ModernCRM,Email system had a problem sending emails,Error,1
361,11/19/2025 23:06,BillingSystem,Email service experienced a sending issue,Error,1
450,10/27/2025 5:59,ThirdPartyAPI,Email delivery system encountered an error,Error,1
477,12-02-2025 10:30,AnalyticsEngine,Email transmission error caused service impact,Critical Error,1
570,11-07-2025 18:08,ThirdPartyAPI,Email service impacted by sending failure,Critical Error,1
678,4/28/2025 15:13,AnalyticsEngine,Email delivery problem affected system,Critical Error,1


In [46]:
cluster_sizes = df['cluster'].value_counts()
large_clusters = cluster_sizes[cluster_sizes > 10].index.tolist()
for cluster_id in large_clusters:
    print(f"\n📌 Cluster {cluster_id} — {cluster_sizes[cluster_id]} log_messages\n")
    cluster_messages = df[df['cluster'] == cluster_id]['log_message'].head(5)
    for msg in cluster_messages:
        print(f"- {msg}")


📌 Cluster 0 — 1017 log_messages

- nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
- nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
- nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
- nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET 

In [76]:
import re
def classify_with_regex(log_message):
    regex_patterns={
        r"User User\d+ logged (out|in)":"User Action",
        r"Backup (started|ended) at .*":"System Notification",
        r"Backup completed successfully.":"System Notification",
        r"System updated to version .*":"System Notification",
        r"File .* uploaded successfully by user .*":"System Notification",
        r"Disk cleanup completed successfully.":"System Notification",
        r"System reboot initiated by user .*":"System Notification",
        r"Account with ID .* created by .*":"User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message,flags=re.IGNORECASE):
            return label
    return None

In [77]:
classify_with_regex("Account with ID 5351 created by User634.")

'User Action'

In [78]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)

In [86]:
df[df.regex_label.notnull()].info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 7 to 2403
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   timestamp     500 non-null    object
 1   source        500 non-null    object
 2   log_message   500 non-null    object
 3   target_label  500 non-null    object
 4   cluster       500 non-null    int64 
 5   regex_label   500 non-null    object
dtypes: int64(1), object(5)
memory usage: 27.3+ KB


<h2>Non Regex</h2>

In [90]:
df_non_regex=df[df.regex_label.isna()].copy()
df_non_regex

,timestamp,source,log_message,target_label,cluster,regex_label
0,27-06-2025 07:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,2,None
3,12-07-2025 00:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0,None
4,02-06-2025 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0,None
...,...,...,...,...,...,...
2405,13-08-2025 07:29,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,0,None
2406,01-11-2025 05:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,7,None
2407,03-08-2025 03:07,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,0,None
2408,11-11-2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,1,None


In [97]:
label_counts = df_non_regex['target_label'].value_counts()
rare_labels = label_counts[label_counts < 5].index
df_non_regex[df_non_regex['target_label'].isin(rare_labels)] #only LegacyCRM source, use LLM classification, rest use bert

,timestamp,source,log_message,target_label,cluster,regex_label
60,06-10-2025 16:55,LegacyCRM,Lead conversion failed for prospect ID 7842 du...,Workflow Error,24,None
255,03-05-2025 16:55,LegacyCRM,API endpoint 'getCustomerDetails' is deprecate...,Deprecation Warning,48,None
377,24-06-2025 12:16,LegacyCRM,Customer follow-up process for lead ID 5621 fa...,Workflow Error,62,None
1325,17-04-2025 07:33,LegacyCRM,Escalation rule execution failed for ticket ID...,Workflow Error,105,None
1734,30-04-2025 07:47,LegacyCRM,The 'ExportToCSV' feature is outdated. Please ...,Deprecation Warning,118,None
1826,23-01-2025 10:33,LegacyCRM,Support for legacy authentication methods will...,Deprecation Warning,122,None
2217,12-05-2025 09:46,LegacyCRM,Task assignment for TeamID 3425 could not comp...,Workflow Error,133,None


In [98]:
df_non_legacy=df_non_regex[df_non_regex['source']!="LegacyCRM"]
df_non_legacy.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [99]:
filtered_embeddings = model.encode(df_non_legacy["log_message"].tolist())
filtered_embeddings[:2]

array([[-1.02939621e-01,  3.35459411e-02, -2.20260732e-02,
         1.55101740e-03, -9.86917876e-03, -1.78956270e-01,
        -6.34409785e-02, -6.01761639e-02,  2.81109158e-02,
         5.99620491e-02, -1.72618348e-02,  1.43363548e-03,
        -1.49560034e-01,  3.15287686e-03, -5.66030927e-02,
         2.71685235e-02, -1.49891041e-02, -3.54037657e-02,
        -3.62936445e-02, -1.45410765e-02, -5.61491773e-03,
         8.75539035e-02,  4.55120578e-02,  2.50963885e-02,
         1.00187510e-02,  1.24267349e-02, -1.39923573e-01,
         7.68696293e-02,  3.14095505e-02, -4.15247958e-03,
         4.36902344e-02,  1.71250012e-02, -8.00951198e-02,
         5.74006326e-02,  1.89091656e-02,  8.55262503e-02,
         3.96398641e-02, -1.34371817e-01, -1.44360063e-03,
         3.06704035e-03,  1.76854044e-01,  4.44885530e-03,
        -1.69274509e-02,  2.24266481e-02, -4.35049310e-02,
         6.09034160e-03, -9.98169929e-03, -6.23972900e-02,
         1.07372422e-02, -6.04895083e-03, -7.14660808e-0

In [103]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

X = filtered_embeddings
y = df_non_legacy['target_label'].tolist() 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = LogisticRegression(max_iter=1000)  
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.989501312335958

Classification Report:
                 precision    recall  f1-score   support

Critical Error       0.92      1.00      0.96        35
         Error       0.96      0.89      0.92        27
   HTTP Status       1.00      1.00      1.00       197
Resource Usage       1.00      1.00      1.00        35
Security Alert       1.00      0.99      0.99        87

      accuracy                           0.99       381
     macro avg       0.98      0.98      0.98       381
  weighted avg       0.99      0.99      0.99       381



In [106]:
np.column_stack((y_test, y_pred))[0:5]


array([['Security Alert', 'Security Alert'],
       ['Resource Usage', 'Resource Usage'],
       ['HTTP Status', 'HTTP Status'],
       ['HTTP Status', 'HTTP Status'],
       ['HTTP Status', 'HTTP Status']], dtype='<U14')

In [105]:
import joblib

joblib.dump(clf, '../models/log_classifier.joblib')

['models/log_classifier.joblib']

In [108]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)